/**
 * `cerefox_get_help` — return curated agent guidance.
 *
 * Layer 3 of the MCP discoverability response (design doc §10d). Bundles
 * `AGENT_QUICK_REFERENCE.md` whole so remote / hosted-MCP / Edge-Function-only
 * agents — who can't read the repo filesystem — have an in-protocol way to
 * discover Cerefox conventions.
 *
 * The bundle is generated by `scripts/bundle_help.ts` from
 * `AGENT_QUICK_REFERENCE.md` and CI-checked by `scripts/check_help_bundle.ts`.
 *
 * Topic filter: case-insensitive substring match against H2 headings (e.g.
 * `topic="links"` matches the section whose heading contains "links",
 * `topic="update"` matches both "Update Workflow" sections). No topic →
 * the full file plus an index of section headings.
 */

import type { MCPSupabaseClient } from "./types.ts";

import { CEREFOX_VERSION } from "../ef-meta/index.ts";
import { editTool } from "./partial-edits.ts";
import { logUsage } from "./_utils.ts";
import {
  HELP_FULL,
  HELP_SECTION_HEADINGS,
  HELP_SECTIONS,
} from "./get-help-content.ts";
import type { ToolContext, ToolDefinition } from "./types.ts";
import { AUTHOR_PARAM_READ, callerIdentity } from "./identity.ts";

/**
 * The operations `cerefox_edit` actually registers, read from its own schema
 * rather than restated — a hand-maintained list here would be the exact drift
 * this block exists to expose.
 *
 * Imported from the tool module directly: `./index.ts` imports this file, so
 * reading the registry would be a cycle.
 */
function editOperations(): string[] {
  const schema = editTool.inputSchema as {
    properties?: {
      operations?: { items?: { properties?: { op?: { enum?: string[] } } } };
    };
  };
  return schema.properties?.operations?.items?.properties?.op?.enum ?? [];
}

/**
 * What an MCP-only agent needs to tell "the server lacks this" from "my client
 * is stale" — the single most-repeated misdiagnosis in reported sessions.
 *
 * Three separate reports have claimed a capability was missing from one server
 * when both were correct and the CLIENT was holding a tool list fetched before
 * an upgrade (clients fetch it once at connect). The advice for a human is
 * "check `cerefox --version`", which is useless to an agent with no shell — and
 * most agents have no shell.
 *
 * So the server states its own version and the operations it actually
 * registers. An agent whose tool list disagrees with this block now knows the
 * disagreement is client-side, without leaving the protocol.
 */
function serverIdentity(): string {
  return [
    "## This server",
    "",
    `- **Version**: ${CEREFOX_VERSION}`,
    `- **cerefox_edit operations**: ${editOperations().join(", ")}`,
    "",
    "**If your tool list disagrees with this block, your CLIENT is out of date, not the server.**",
    "MCP clients fetch the tool list once when they connect and cache it, so a server",
    "upgraded mid-session is invisible until the client reconnects. Ask the user to restart",
    "the client — and if it stays missing after a restart, the client config may pin an old",
    "version of the package. Do not record a capability difference between the local and",
    "remote servers: they run the same code, and every such report so far has been a stale",
    "client.",
  ].join("\n");
}

async function handler(
  supabase: MCPSupabaseClient,
  args: Record<string, unknown>,
  ctx: ToolContext,
): Promise<string> {
  const topic = (args.topic as string | undefined)?.trim();

  logUsage(supabase, {
    operation: "get_help",
    accessPath: ctx.accessPath,
    requestor: callerIdentity(args),
    query_text: topic ?? null,
    result_count: 1,
  });

  // The identity block leads EVERY response, not just `topic: "server"`.
  //
  // Behind a topic name it had a bootstrap problem an agent caught immediately:
  // the remedy for a stale server requires a server new enough to contain the
  // remedy. Asked for "server" on a pre-1.5.0 deployment, they got "no such
  // topic" and reasonably concluded the documented check did not exist — inside
  // the very section warning against unverified infrastructure claims.
  //
  // Nothing can retrofit old servers. What this fixes is the need to know a
  // magic word: any `cerefox_get_help()` call now shows the version, and the
  // ABSENCE of this block is itself diagnostic — a server that does not print
  // it predates 1.5.0.
  if (!topic) {
    const idx = HELP_SECTION_HEADINGS.map((h) => `  - ${h}`).join("\n");
    return (
      serverIdentity() +
      "\n\n---\n\n" +
      HELP_FULL +
      "\n\n---\n\n" +
      "## Available topics\n\n" +
      "Call `cerefox_get_help(topic: \"<heading>\")` to retrieve a single section.\n\n" +
      idx +
      "\n\n(Topic match is case-insensitive substring on the headings above.)"
    );
  }

  // `topic: "server"` / `"version"` is the self-check, and must work even
  // though this section is not part of the bundled markdown.
  if (/^(server|version|stale|client)$/i.test(topic)) return serverIdentity();

  const t = topic.toLowerCase();
  const matched = HELP_SECTION_HEADINGS.filter((h) => h.toLowerCase().includes(t));

  if (matched.length === 0) {
    return (
      serverIdentity() +
      "\n\n---\n\n" +
      `No help topic matched "${topic}".\n\n` +
      `Available topics:\n` +
      HELP_SECTION_HEADINGS.map((h) => `  - ${h}`).join("\n") +
      "\n\nCall `cerefox_get_help()` with no topic for the full document."
    );
  }

  return serverIdentity() + "\n\n---\n\n" + matched.map((h) => HELP_SECTIONS[h]).join("\n\n---\n\n");
}

export const getHelpTool: ToolDefinition = {
  name: "cerefox_get_help",
  description:
    "Retrieve Cerefox's own agent-usage guidance (the AGENT_QUICK_REFERENCE.md content). Call with no arguments to get the full reference + a section index. Call with `topic` to get a single section (case-insensitive substring match against H2 headings). Use this whenever you're uncertain about Cerefox conventions — link forms, project-membership semantics, update workflows, etc.",
  // Read-only: touches nothing. Safe for a client to run without prompting.
  annotations: {
    title: "Read Cerefox conventions",
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false,
  },
  inputSchema: {
    type: "object",
    properties: {
      topic: {
        type: "string",
        description:
          'Optional. Case-insensitive substring against H2 headings (e.g. "links", "update", "metadata"). Omit for the full reference.',
      },
      author: AUTHOR_PARAM_READ,
    },
  },
  handler,
};
